### ISSUE TITLE
todo: site features

### ISSUE THREAD

**Issue by jonschlinkert** [handlebars-lang/docs#4]
Please feel free to add comments, feedback, or pushback on any of these. I (or anyone with edit rights) can update this list based on feedback in the comments.

**Style / layout**

I have no preference regarding the style at all. Please feel free to give suggestions or point out sites that you love. 

For the most part, the templates and markdown content will be relatively unaffected by the styling decisions we make. Thus, for the time being, I'm going to just implement a basic site with default theme that gives us something to visualize, then we can completely change that later when we decide on the "real" theme/design.

**Areas**

Just thinking out loud... feedback would be great.

- [ ] home
- [ ] examples / recipes
- [ ] API / documentation 
- [ ] community (?)
- [ ] blog (?) 

**Search**

We can use any solution for this. If no one objects, I recommend using algolia.

**Comment by nknapp** [comment]
I thought

- [ ] home (@wycats wish was to include basic examples for templates, builtins (`if`, `each`), custom helpers, custom block-helpers, like it is on the current page).
- [ ] **language-features**: A list of pages with more detailed explanations and examples for each language-feature (basic substitutions, blocks, context, partials, `{{inline (helpers)}}`, white-space control, decorators). Each feature-page should contain examples.
- [ ] **differences to mustache**

I wouldn't put too much emphasize on the javascript implementation in this part. It is a reference implementation, but the great thing about handlebars is, that there are implementations in many languages and [handlebars.js](https://github.com/wycats/handlebars.js) is only the reference implementation of the handlebars language.

- [ ] **implementations/using handlebars** a list of implementations that includes `handlebarsjs.com` as reference implementation. (was that what you mean by "community")

**Search**

I actually thought about something in browser like [lunr](https://lunrjs.com/) and not about a cloud service. What happens if we get over the limits of the free account?

**Comment by nknapp** [comment]
I even thought about moving the details of handlebars-js to the README on github, but that would certainly be controversial. A usage example for in-browser and NodeJS should probably be on the site itself.

**Comment by jonschlinkert** [comment]
> I thought

all of that makes sense. I'll do a rough pass and we can change as we go. 

> What happens if we get over the limits of the free account?

Good question. I forgot about that, I think we were going to contact someone there and ask if they would sponsor search for one of our sites. I can check into that. We've used lunr as well. There are tradeoffs in both cases, but either is fine.

**Comment by nknapp** [comment]
> Which details in particular? I'm not sure what you mean

Installation, usage example. When I talk about "examples" in the "language-feature"-section,
I mean examples like `My name is {{name}}` plus `{ "name": "Nils" }` leads to `My name is Nils`.
Those examples should work in every implementation that is compatible to Handlebars.js.

But texts that are specific to the JavaScript-implementation could also be in the README of the github-repo like:

"In order to use Handlebars in NodeJS, run `npm install handlebars` and then use `var Handlebars = require('handlebars'); var template = Handlebars.compile('{{name}}'); template({ name: 'Nils' });`
 
```

**Comment by jonschlinkert** [comment]
So basically "just enough" information on the readme to help newcomers understand what handlebars.js is, and what it does, and how to get started, then direct them to the website for more?

**Comment by yonHolmes** [comment]
A "copy to clipboard" button on the Playground's "Output" section would be massively useful, or even if it was a text box light the other 3; you can't CTRL+A into it as that selects the whole page.

**Comment by nknapp** [comment]
@yonHolmes I think you problem should be solved by now, right?

**Comment by yonHolmes** [comment]
Not as far as I can see: https://handlebarsjs.com/examples/helper-block.html

**Comment by nknapp** [comment]
I think I changed the output to an editor, so Ctrl+A should working

**Comment by yonHolmes** [comment]
Yup I can now do CTRL+A, thanks
